### PR TITLE
Add plugin support

### PR DESCRIPTION
**Pull request by sohamkamani**
Plugins add support for sending request metrics, and logging #2

### CODE REVIEW

**Comment by rShetty** [comment]
@sohamkamani A major change to the structure of the API has landed on master, can you plz rebase with master and inculcate the new changes. Thanks

**Comment by sohamkamani** [comment]
@rShetty fixed

**Comment by rShetty** [comment]
@sohamkamani You want to look at fixing merge conflicts, will have a look and merge it

**Comment by sohamkamani** [comment]
@rShetty Yes! Will look at the conflicts and let you know!

**Comment by rShetty** [comment]
@sohamkamani Coverage 🤔

**Comment by sohamkamani** [comment]
ya its a bit misleading since I added the mock to the main package.. fixing this

**Comment by sohamkamani** [comment]
@rShetty is this ok to be merged?

**Comment by rShetty** [comment]
@sohamkamani Will review this, sorry for the delay, caught up with multiple things. Will review so soon. thanks

**Comment by jjafuller** [comment]
Has there been any progress on this? I was just about to wire in httptrace, but I would rather use this if possible.

**Comment by unmultimedio** [comment]
Hello, is there any progress on this? Is this repo still being maintained?

**Pull request merged**
