### PR TITLE
adding change to reuse connections

### PR DESCRIPTION
**Pull request by Matias-Barrios**

### CODE REVIEW

**Review by psaintgirons — APPROVED** [review]

**Comment by luca147** [comment]
Currently I'm facing this issue, the connection is never used

**Comment by Gabrieljev** [comment]
when is the release date for this issue?

**Comment by Matias-Barrios** [comment]
@Gabrieljev I did not get your question. Do you want to know when we are merging this? If thats the question then the response would be asap. It depends on the authors replying to the issue.

**Comment by saravind-hotstar** [comment]
@gowtham-sai Please can we merge this, this actually affects performance

**Comment by Nydan** [comment]
Hi, @saravind-hotstar I am no longer has the access to merge this PR. 
Please contact the other maintaner whom has access to merge.

**Comment by rajat25** [comment]
@Matias-Barrios Can we please merge this PR? This seems to be a real performance issue.

**Review by rajat25 — APPROVED** [review]

**Comment by rajat25** [comment]
@rShetty Can we please merge this PR?
This would fix a performance issue.

**Comment by gwthm-in** [comment]
@rajat25 My user id changed and hence didn't get the notification for this. I'll try to close this as soon as possible.

**Review by gwthm-in — APPROVED** [review]

**Pull request merged**
