### PR TITLE
Add examples for functional options

### PR DESCRIPTION
**Pull request by sohamkamani**

### CODE REVIEW

**Comment by italolelis** [comment]
Cool PR. Maybe we can add the examples for both `httpclient` and `hystrixclient` on a `examples` directory?

**Comment by rShetty** [comment]
@sohamkamani Can we also add examples for hystrix client plz ?

**Comment by rShetty** [comment]
@sohamkamani Can we also add examples for hystrix client plz ?

**Comment by sohamkamani** [comment]
Yes, added them :)

**Comment by rShetty** [comment]
@sohamkamani Hey does it make sense to put these examples in its own folder, instead of in tests ?

**Comment by sohamkamani** [comment]
The suggested way to do it in Go is with test examples. These will appear in the docs, and be tested in CI automatically. Any reason you prefer the example folder?

**Comment by italolelis** [comment]
If we decide to put it in the tests we should probably do it in a separate file, as suggested [here](https://blog.golang.org/examples#TOC_2.), wdyt?

**Comment by rShetty** [comment]
@sohamkamani Can we move it to a separate file maybe ? Tests and examples in the same file feels a bit confusing

**Comment by rShetty** [comment]
@sohamkamani Can you help fix the above plz ?

**Pull request closed without merging**
