### PR TITLE
Net http error quoting

### PR DESCRIPTION
**Pull request by johanavril**
fix fail unit test caused by changes in go net/url error message
[original PR](https://github.com/golang/go/pull/29384/files#diff-6c2d018290e298803c0c9419d8739885R29) in go

fix typo in the unit test

### CODE REVIEW

**Comment by johanavril** [comment]
tried rebuild the travis CI build, but still failing
all unit test already passed

**Comment by rShetty** [comment]
@johanavril Thanks for the PR. checking this.

**Comment by rShetty** [comment]
@johanavril Which version of go are you using? I tested it on go 1.13 and tests are working fine.

**Comment by johanavril** [comment]
@rShetty it works just fine on go 1.13. but the go used in the travis CI use the one from master branch not a released version. I don't know which version of go will implement that changes, but currently the travis CI will fail on the unit test phase.

**Comment by rShetty** [comment]
@johanavril Earlier it was using the master build of golang, I have changed it to point to the latest stable release go-1.13.6. The tests on the master are working fine now. We should make the above-proposed change once we move to the next stable build. Thoughts?

**Comment by johanavril** [comment]
@rShetty I agree, that should be the best move.

**Comment by rShetty** [comment]
@johanavril Thanks for this. Closing this for now.

**Comment by johanavril** [comment]
hi @rShetty , go 1.14 has been released, and the changes on the error quoting is also on the 1.14 version. I think it would be better to update go version on .travis.yml and re-open this PR, any thoughts ?

**Pull request closed without merging**
